### ISSUE TITLE
Develop a system for storing multiple bases for each class

### ISSUE THREAD

**Issue by zer0main** [LuaAndC/luawt#53]
It's just a name (string) of one base at the moment. :-1:

**Comment by starius** [comment]
Do we really need it? Multiple inheritance can be very complicated.

**Comment by zer0main** [comment]
We're not able to limit our users in this question, because they may need to use this feature (e.g. passing inheritors objects to functions where bases pointers are expected).
Otherwise, how to choose between bases and select one to store it (others would be ignored).

**Comment by starius** [comment]
Multiple bases in our metatable make sense only if at least two of them are descendants of WObject. (Bases that are not descendants of WObject do not exist as classes for our system.) Are we going to bind such a class of Wt which satisfies this criteria?
